---
title: "Sanggala Corridor Project"
subtitle: "Rapid Survey T=0 ARR Dashboard"
author: "Syuryadi Wijaya"
format: 
  dashboard:
    theme: cosmo
    orientation: rows
    nav-buttons:
      - icon: github
        href: https://github.com/
    css: style.css 
execute:
  echo: false
  warning: false
  message: false
---

```{r}
#| label: setup
#| include: false

# 1. Panggil library dan package terlebih dahulu
library(dplyr)
library(tidyverse)
library(plotly)

# 2. Baru panggil script backend di bagian bawah
source("01 - Rapid Survey Analysis (Land cover).R")
```

# Analisis Statistik  {icon="bar-chart-fill"}

## Row  {height="55%"}

### Column  {width="50%"}

```{r}
#| title: "Distribusi Tutupan Lahan"
p1 <- ggplotly(plot_landcover, tooltip = c("y", "fill"))
p1$x$layout$margin$b <- 40
p1
```

### Column  {width="50%"}

```{r}
#| title: "Status Pengelolaan Lahan"
p2 <- ggplotly(plot_status_lahan, tooltip = c("y", "fill"))
p2 <- layout(p2, showlegend = FALSE)
p2
```

## Row  {height="45%"}

### Column

```{r}
#| title: "Top 10 Vegetasi Dominan"
p3 <- ggplotly(plot_vegetation, tooltip = c("x", "y"))
p3 <- layout(p3, showlegend = FALSE)
p3
```

# Pemetaan Spasial  {icon="map-fill"}

## Row  {height="100%"}

### Column

```{r}
#| title: "Peta Ground Check Land Cover - 2026"
peta_spasial
```
